# Generated by Django 4.2.2 on 2023-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category_rewiew_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiew',
            name='stars',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Звезды'),
        ),
    ]
