# Generated by Django 4.2.2 on 2023-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
