# Generated by Django 4.2.2 on 2023-07-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.ManyToManyField(null=True, related_name='color', to='product.product'),
        ),
    ]
